apiVersion: v1
kind: ConfigMap
metadata:
  name: bankme-rabbitmq-envs
  namespace: bankme
data:
  RABBITMQ_DEFAULT_HOST: "rabbitmq-svc"
  RABBITMQ_DEFAULT_USER: "rabbitmq"
  RABBITMQ_DEFAULT_PASS: "rabbitmq"
