kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-svc
  namespace: bankme
spec:
  type: ClusterIP
  selector:
    app: bankme-rabbitmq
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
