# Etapa 1: Build do aplicativo Angular
FROM node:alpine as build

WORKDIR /app

# Copiar os arquivos package.json e package-lock.json
COPY package*.json ./

# Instalar as dependências do Angular
RUN npm install -g @angular/cli

RUN npm install

# Copiar o código-fonte do aplicativo
COPY . .

# Construir o aplicativo Angular
RUN ng build

# Etapa 2: Configuração do NGINX
FROM nginxinc/nginx-unprivileged

# Copie os arquivos do build para o diretório padrão do NGINX
COPY --from=build /app/dist/client/browser /usr/share/nginx/html

# Copie o arquivo de configuração do NGINX
COPY etc/nginx/nginx.conf /etc/nginx/nginx.conf

# Exponha a porta 80 (NGINX usa a porta 80 internamente)
EXPOSE 80

# Comando para iniciar o NGINX
CMD ["nginx", "-g", "daemon off;"]
