@baseUrl = http://localhost:8080

### Create a new assignor
POST {{baseUrl}}/integrations/assignor
Content-Type: application/json

{
    "document": "123.456.789-00",
    "email": "joao@mail.com",
    "phone": "99 99999-9999",
    "name": "João da Silva"
}

### Read all assignors
GET {{baseUrl}}/integrations/assignor

### Read one assignor
GET {{baseUrl}}/integrations/assignor/84a822df-58c6-4dc8-b9a4-b63f500f2ba2

