@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6ImFwcm92YW1lIiwicGFzc3dvcmQiOiJhcHJvdmFtZSIsImlhdCI6MTcxNjU5NTc5OCwiZXhwIjoxNzE2NTk1ODU4fQ.TjTnnl5LwAK3JH9dypiRUpI2K1AEiuiK2VvQCf35bxo

### Create a new assignor
POST {{baseUrl}}/integrations/assignor
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "document": "123.456.789-00",
    "email": "joao@mail.com",
    "phone": "99 99999-9999",
    "name": "João da Silva"
}

### Read all assignors
GET {{baseUrl}}/integrations/assignor
Authorization: Bearer {{token}}

### Read one assignor
GET {{baseUrl}}/integrations/assignor/00e44aec-4fd6-43d0-b151-625e429ff995
Authorization: Bearer {{token}}

### Update an assignor 
PATCH {{baseUrl}}/integrations/assignor/0f23f87f-d760-4169-8df0-02d8af8d2215
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "joao.silva@mail.com"
}

### Delete an assignor
DELETE {{baseUrl}}/integrations/assignor/0f23f87f-d760-4169-8df0-02d8af8d2215
Authorization: Bearer {{token}}
