@baseUrl = http://localhost:8080

### Create a new assignor
POST {{baseUrl}}/integrations/assignor
Content-Type: application/json

{
    "document": "123.456.789-00",
    "email": "joao@mail.com",
    "phone": "99 99999-9999",
    "name": "João da Silva"
}

### Read all assignors
GET {{baseUrl}}/integrations/assignor

### Read one assignor
GET {{baseUrl}}/integrations/assignor/84a822df-58c6-4dc8-b9a4-b63f500f2ba2

### Update an assignor 
PATCH {{baseUrl}}/integrations/assignor/0f23f87f-d760-4169-8df0-02d8af8d2215
Content-Type: application/json

{
    "email": "joao.silva@mail.com"
}

### Delete an assignor
DELETE {{baseUrl}}/integrations/assignor/0f23f87f-d760-4169-8df0-02d8af8d2215
