FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm install -g @angular/cli
COPY . .
# RUN npm run build
EXPOSE 4200
CMD ng serve --host 0.0.0.0 --proxy-config=src/proxy.docker.json