version: 0.2

on:
  worflow_dispatch:
  push:
    branches:
      - main

phases:
  pre_build:
    commands:
     -  aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 099289132084.dkr.ecr.us-east-2.amazonaws.com

  build:
    commands:
    - docker-compose build -t challenge
    - docker tag challenge:latest 099289132084.dkr.ecr.us-east-2.amazonaws.com/challenge:latest

  post_build:
    commands:
    - docker push 099289132084.dkr.ecr.us-east-2.amazonaws.com/challenge:latest