services:
  api:
    container_name: bankme-api
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 3333:3333
    volumes:
      - ./packages/api:/home/node/app
      - ./node_modules:/home/node/app/node_modules
