services:
  backend:
    container_name: aproveme-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=file:/data/sqlite.db
      - RABBITMQ_URL=amqp://rabbitmq:5672
    restart: always
    volumes:
      - ./backend/prisma:/data
    command: >
      sh -c "npx prisma migrate deploy && npm run start:prod"

  frontend:
    container_name: aproveme-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/integrations
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
