services:
  backend:
    container_name: aproveme-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=file:/data/sqlite.db
    restart: always
    volumes:
      - ./backend/prisma:/data
    command: >
      sh -c "npx prisma migrate deploy && npm run start:prod"
