version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    container_name: app-server
    environment:
      DATABASE_URL: "file:./dev.db"
      JWT_SECRET: "mz5kapt42bbzyy462xjz6uprw3wrbogznfztf65j4ub7gxr9z9d8k9xy6tf75pvwvhme49lb"
      JWT_ISSUER: "aprove-me-api"
      JWT_AUDIENCE: "auth-user"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    ports:
      - 3000:3000

  redis:
    container_name: "app-redis"
    image: bitnami/redis
    restart: always
    ports:
      - '6379:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
