services:
  api:
    container_name: bankme-api
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 3333:3333
    volumes:
      - ./packages/api:/home/node/app
      - ./node_modules:/home/node/app/node_modules

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: "rmq"
      RABBITMQ_DEFAULT_PASS: "rmq"
