services:
  api:
    container_name: bankme-api
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 3333:3333
    volumes:
      - ./packages/api/prisma:/home/node/app/prisma
    depends_on:
      - rabbitmq
    networks:
      - bankme

  web:
    container_name: bakme-web
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - bankme

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bankme-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: "rmq"
      RABBITMQ_DEFAULT_PASS: "rmq"
    networks:
      - bankme

networks:
  bankme:
    driver: bridge
