version: '3'

services:

  rabbitmq:
   image: rabbitmq:3-management
   container_name: rabbitmq-my
   ports:
     - "5672:5672"
     - "15672:15672"
   volumes:
     - rabbitmq_data:/var/lib/rabbitmq

  api:
    build: ./backend/
    container_name: bankme_api
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./backend/src:/app/backend/src
volumes:
  rabbitmq_data: