version: '3.8'
services:
  api:
    container_name: api
    build:
      context: ./
      target: deps
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "start:dev"]
    env_file:
      - .env
    environment:
      - REDIS_HOST=api_redis
      - REDIS_PORT=6379
    ports:
      - 3000:3000
    networks:
      - nesjs-network
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    restart: unless-stopped

  api_redis:
    container_name: api_redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

networks:
  nesjs-network: