version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  run_tests:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Run Tests
          command: npm run test --ci --runInBand --reporters=default --reporters=jest-junit


  build_and_deploy:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Build Application
          command: npm run build
      - run:
          name: Install Heroku CLI
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Deploy to Heroku
          command: |
            echo $HEROKU_API_KEY | heroku auth:token
            git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git
            git push heroku main
      - run:
          name: Scale Dynos
          command: heroku ps:scale web=1 --app $HEROKU_APP_NAME

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
      - build_and_deploy:
          requires:
            - run_tests