### Get all Assignors
GET http://localhost:3000/integrations/assignor
# Replace your token in Authorization header
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNmQ2NjhjMy1lYWQzLTRjNGMtYWNkMS1lODM2YTg0YmZkM2UiLCJsb2dpbiI6Im5lYXRoIiwiaWF0IjoxNzE2NjgzNTc2LCJleHAiOjE3MTcyODgzNzZ9.S_XvTFqRWgloINgVdG6FhJC5p-CC-n7MkILlpLF20KU

### Get Assignor by ID
GET http://localhost:3000/integrations/assignor/228f7f74-90de-4e8a-94a0-d320795a20dc
# Replace your token in Authorization header
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNmQ2NjhjMy1lYWQzLTRjNGMtYWNkMS1lODM2YTg0YmZkM2UiLCJsb2dpbiI6Im5lYXRoIiwiaWF0IjoxNzE2NjgzNTc2LCJleHAiOjE3MTcyODgzNzZ9.S_XvTFqRWgloINgVdG6FhJC5p-CC-n7MkILlpLF20KU

### Create Assignor
POST http://localhost:3000/integrations/assignor
Content-Type: application/json
# Replace your token in Authorization header
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNmQ2NjhjMy1lYWQzLTRjNGMtYWNkMS1lODM2YTg0YmZkM2UiLCJsb2dpbiI6Im5lYXRoIiwiaWF0IjoxNzE2NjgzNTc2LCJleHAiOjE3MTcyODgzNzZ9.S_XvTFqRWgloINgVdG6FhJC5p-CC-n7MkILlpLF20KU

{
  "document": "12345678901",
  "email": "teste@teste.com",
  "phone": "31 99999-9999",
  "name": "Teste do teste"
}

### Update Assignor
PATCH  http://localhost:3000/integrations/assignor/228f7f74-90de-4e8a-94a0-d320795a20dc
Content-Type: application/json
# Replace your token in Authorization header
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNmQ2NjhjMy1lYWQzLTRjNGMtYWNkMS1lODM2YTg0YmZkM2UiLCJsb2dpbiI6Im5lYXRoIiwiaWF0IjoxNzE2NjgzNTc2LCJleHAiOjE3MTcyODgzNzZ9.S_XvTFqRWgloINgVdG6FhJC5p-CC-n7MkILlpLF20KU

{
  "document": "12345678951",
  "email": "teste2@teste.com"
}

### Delete Assignor
DELETE http://localhost:3000/integrations/assignor/228f7f74-90de-4e8a-94a0-d320795a20dc
# Replace your token in Authorization header
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNmQ2NjhjMy1lYWQzLTRjNGMtYWNkMS1lODM2YTg0YmZkM2UiLCJsb2dpbiI6Im5lYXRoIiwiaWF0IjoxNzE2NjgzNTc2LCJleHAiOjE3MTcyODgzNzZ9.S_XvTFqRWgloINgVdG6FhJC5p-CC-n7MkILlpLF20KU
