### Get all Payables
GET http://localhost:3000/integrations/payable
# Replace your token in Authorization header
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNmQ2NjhjMy1lYWQzLTRjNGMtYWNkMS1lODM2YTg0YmZkM2UiLCJsb2dpbiI6Im5lYXRoIiwiaWF0IjoxNzE2NjgzNTc2LCJleHAiOjE3MTcyODgzNzZ9.S_XvTFqRWgloINgVdG6FhJC5p-CC-n7MkILlpLF20KU


### Get Payable by ID
GET http://localhost:3000/integrations/payable/36911613-6d2a-4a10-b23e-fdaa6df6c95d
# Replace your token in Authorization header
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNmQ2NjhjMy1lYWQzLTRjNGMtYWNkMS1lODM2YTg0YmZkM2UiLCJsb2dpbiI6Im5lYXRoIiwiaWF0IjoxNzE2NjgzNTc2LCJleHAiOjE3MTcyODgzNzZ9.S_XvTFqRWgloINgVdG6FhJC5p-CC-n7MkILlpLF20KU


### Create Payable
POST http://localhost:3000/integrations/payable
Content-Type: application/json
# Replace your token in Authorization header
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNmQ2NjhjMy1lYWQzLTRjNGMtYWNkMS1lODM2YTg0YmZkM2UiLCJsb2dpbiI6Im5lYXRoIiwiaWF0IjoxNzE2NjgzNTc2LCJleHAiOjE3MTcyODgzNzZ9.S_XvTFqRWgloINgVdG6FhJC5p-CC-n7MkILlpLF20KU

{
  "value": 500,
  "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc"
}

### Update Payable
PATCH  http://localhost:3000/integrations/payable/36911613-6d2a-4a10-b23e-fdaa6df6c95d
Content-Type: application/json
# Replace your token in Authorization header
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNmQ2NjhjMy1lYWQzLTRjNGMtYWNkMS1lODM2YTg0YmZkM2UiLCJsb2dpbiI6Im5lYXRoIiwiaWF0IjoxNzE2NjgzNTc2LCJleHAiOjE3MTcyODgzNzZ9.S_XvTFqRWgloINgVdG6FhJC5p-CC-n7MkILlpLF20KU


{
  "value": 1000
}

### Delete Payable
DELETE http://localhost:3000/integrations/payable/36911613-6d2a-4a10-b23e-fdaa6df6c95d
# Replace your token in Authorization header
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNmQ2NjhjMy1lYWQzLTRjNGMtYWNkMS1lODM2YTg0YmZkM2UiLCJsb2dpbiI6Im5lYXRoIiwiaWF0IjoxNzE2NjgzNTc2LCJleHAiOjE3MTcyODgzNzZ9.S_XvTFqRWgloINgVdG6FhJC5p-CC-n7MkILlpLF20KU



### Post Payables in batch
POST http://localhost:3000/integrations/payable/batch
Content-Type: application/json
# Replace your token in Authorization header
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNmQ2NjhjMy1lYWQzLTRjNGMtYWNkMS1lODM2YTg0YmZkM2UiLCJsb2dpbiI6Im5lYXRoIiwiaWF0IjoxNzE2NjgzNTc2LCJleHAiOjE3MTcyODgzNzZ9.S_XvTFqRWgloINgVdG6FhJC5p-CC-n7MkILlpLF20KU

[
  { "value": 10, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 20, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 30, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 40, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 50, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 60, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 70, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 80, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 90, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 100, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 110, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 120, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 130, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 140, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 150, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 160, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 170, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 180, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 190, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" },
  { "value": 200, "assignorId": "228f7f74-90de-4e8a-94a0-d320795a20dc" }
]


