FROM node:16-alpine AS build

WORKDIR /home/node/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Estágio 2: Configurar o Nginx para servir a aplicação construída
FROM nginx:alpine

COPY --from=builder /app/dist/recebiveis-front /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]