FROM node:19-slim

## como a imagem ja vem com uma pasta node usaremos ela como foder de trabalho
WORKDIR /home/node/app
## para desenvolvimento deixaremos o container up ate que seja fechado.

CMD ["tail" , "-f" , "/dev/null"]

