version: "3.8"

services:
  app:
    container_name: aproveme-prisma-app
    image: node:20
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "file:/app/data/sqlite/dev.db"
    volumes:
      - .:/app    # Mapeando o diretório raiz do projeto para /app no contêiner
    working_dir: /app
    command: ["node", "dist/src/infra/main.js"]  # Atualize o caminho para o seu main.js
