version: "3.8"

services:
  sqlite3:
    container_name: aproveme-prisma-app
    image: nouchka/sqlite3
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "file:./db/dev.db" # URL do SQLite para o Prisma
    volumes:
      - ./data/sqlite:/data/sqlite