version: '3.8'

services:
  db-dev-payable-service:
    container_name: db-dev-payable-container
    networks: [backend]
    image: postgres:16.3-alpine3.19
    ports: [5432:5432]
    volumes:
      - ./container-data/postgres:/data/postgres
      - ./initial-sql/:/docker-entrypoint-initdb.d/
    env_file: [./.postgres.env]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  backend:
    name: payable-network
