GET http://localhost:3333/integrations/assignor

###

GET http://localhost:3333/integrations/assignor/a1a3f1ea-5b03-4f31-8c8d-a5a0a2010999
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYjU3YzI3ZC0xMDMxLTQxN2MtYjAyNy03N2FkYzQ3ZjRlYzkiLCJsb2dpbiI6InJpY2FyZG8iLCJpYXQiOjE3MDg4NjA4OTYsImV4cCI6MTcwODg2NDQ5Nn0.roiObwOZ6GknlzbnZIduUhd1ZUhD6YoCA07StZ8XSaU

###

POST http://localhost:3333/integrations/assignor
Content-Type: application/json

{
  "document": "123.456.789-10",
  "email": "fulano@tal.com",
  "phone": "11 99999-9999",
  "name": "Fulano de Tal"
}

###

PATCH http://localhost:3333/integrations/assignor/a1a3f1ea-5b03-4f31-8c8d-a5a0a2010999
Content-Type: application/json

{
  "email": "ciclano@tal.com",
  "name": "Ciclano"
}

###

DELETE http://localhost:3333/integrations/assignor/a1a3f1ea-5b03-4f31-8c8d-a5a0a2010999

###
