version: '3'
services:
  redis:
    image: redis:latest
    container_name: b-redis
    restart: on-failure
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
volumes:
  redis-data:
